version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile

  catalogo:
    image: ${DOCKER_REGISTRY-}catalogo
    build:
      context: .
      dockerfile: Catalogo/Dockerfile


  pedido:
    image: ${DOCKER_REGISTRY-}pedido
    build:
      context: .
      dockerfile: Pedido/Dockerfile


  rpcclient:
    image: ${DOCKER_REGISTRY-}rpcclient
    build:
      context: .
      dockerfile: RPCClient/Dockerfile
    container_name: RPCClient

  rpcserver:
    image: ${DOCKER_REGISTRY-}rpcserver
    build:
      context: .
      dockerfile: ../RPCServer/Dockerfile
    container_name: RPCServer