version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile

  catalogo:
    image: ${DOCKER_REGISTRY-}catalogo
    build:
      context: .
      dockerfile: Catalogo/Dockerfile


  pedido:
    image: ${DOCKER_REGISTRY-}pedido
    build:
      context: .
      dockerfile: Pedido/Dockerfile


  venda:
    image: ${DOCKER_REGISTRY-}venda
    build:
      context: .
      dockerfile: Venda/Dockerfile


  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile